apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitemplate-service-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apitemplate-service-golang
  template:
    metadata:
      labels:
        app: apitemplate-service-golang
    spec:
      containers:
        - name: apitemplate-service-golang
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 8024
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: MONGO_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: DATABASE_NAME
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: BASE_URL
            - name: BLOODCHAIN_API_URL
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: BLOODCHAIN_API_URL
            - name: BACKENDURL
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: BACKENDURL
            - name: TOKEN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: TOKEN_PASSWORD
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: apitemplate-service-golang
                  key: ENVIRONMENT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          volumeMounts:
            - name: service-account-credentials-volume
              mountPath: /etc/gcp
              readOnly: true
      volumes:
        - name: service-account-credentials-volume
          secret:
            secretName: apitemplate-service-golang
            items:
              - key: SA_JSON
                path: sa_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: apitemplate-service-golang
  labels:
    app: apitemplate-service-golang
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8024
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: apitemplate-service-golang